### ISSUE TITLE
Problem with eshop link

### ISSUE THREAD

**Issue by cosmo0** [benbarden/switchscores#107]
In the "games without category" page it looks like it has a link:

![image](https://user-images.githubusercontent.com/3973850/121380264-047a9180-c945-11eb-9e30-d27804cb17b0.png)

But when I open the game it doesn't:

![image](https://user-images.githubusercontent.com/3973850/121380413-22e08d00-c945-11eb-98da-9acdb73180ca.png)

**Comment by benbarden** [comment]
This is because it was linked to a game in the API that was deleted after being linked.

There are a few changes I've made to make this better:

- the list page will now show a broken link if this happens - https://www.switchscores.com/staff/games/list/no-category
- the detail page will show that the link is broken, but still linked to an ID - https://www.switchscores.com/staff/games/detail/5986
- also on that page, the logic for showing a link , a broken link, or "Not linked" is now more reliable
- and that page will now show the format options - de-listed is one of them. Previously, it was displayed in conjunction with the eShop link - now you can see it separately
- editing the link and leaving it blank will fix the issue, although it will also delete any images - so it would be best not to change them unless absolutely necessary - hopefully the broken link is clear enough

Hopefully this solves this issue and a few others, too.

**Comment by benbarden** [comment]
Slight correction: editing the link and leaving it blank won't delete images - so I can fix those if there are any de-listed games that are causing issues.

**Comment by cosmo0** [comment]
Thanks! This'll work.
