### ISSUE TITLE
Suggestion: improve ranking display

### ISSUE THREAD

**Issue by cosmo0** [benbarden/switchscores#11]
In the game's page ( https://www.switchscores.com/games/5081/when-the-past-was-around ) on the top right (rank):

- display the "top %": "All-time 17 / 2447 (top 5%)" with top 50, 25, 10 and 5%. Don't display if it's not even in the top 50%.
- add the category ranking in the box

**Comment by benbarden** [comment]
Probably not a big job. Category ranking is bigger though, as these values are recalculated and stored in the DB rather than being generated on each page load. Perhaps category ranking could be another issue?

**Comment by cosmo0** [comment]
You pre-compute ranking? I would have done a sub-query, something like:

````sql
select
  g.id, g.name, etc,
  (select count(*) from games allg where allg.category_id = g.category_id) as games_in_category
from games g
where id = @id
````

It's not very clean, but with at most 300-400 games in a category and a few indexes, I don't think it would be a problem performance-wise?

**Comment by benbarden** [comment]
Each game has a rank value for all-time, release year, and release year/month (e.g. 2017 March). To be able to get a game's rank (e.g. No 1, No 2, No 3), you also need to know the ranks of other games, too. That is more difficult to do if you don't have the values stored. Maybe I'm missing an easier way to do it.

I pre-calculate quite a lot of things - because:

1. it's less work for the site to do. There are lots of calculated values, and they don't change often enough to make it worthwhile for them to be calculated live.
2. I find that it's faster/easier to reference values in queries or in code if you don't have to calculate them first.

**Comment by cosmo0** [comment]
> To be able to get a game's rank (e.g. No 1, No 2, No 3), you also need to know the ranks of other games, too.

I forgot about that haha ^^'

But maybe it could just be another sub-query. Like

````sql
  (select count(*) from games betterg where betterg.category_id = g.category_id and betterg.score > g.score) as better_games_in_category
````

But yeah pre-calculated things are good too if they're not too bothersome to manage and it helps elsewhere. Maybe in a dedicated table? Or maybe "rank in the category" is not a big enought deal for so much work lol
