### ISSUE TITLE
Fix broken store override URLs

### ISSUE THREAD

**Issue by benbarden** [benbarden/switchscores#144]
In fixing #140 I found a couple of broken store override URLs that need fixing or blanking out:

https://www.switchscores.com/games/3711/one-finger-death-punch-2

https://www.switchscores.com/games/7056/real-time-battle-shogi-online

https://www.switchscores.com/games/7107/duel-princess - URL appears to be valid but is hanging, so I've blanked it out: https://www.nintendo.co.uk/Games/Nintendo-Switch-download-software/Duel-Princess-2098295.html

https://www.switchscores.com/games/7336/duggy - URL is hanging, so I've blanked it out: https://www.nintendo.co.uk/Games/Nintendo-Switch-download-software/Duggy-2166152.html

https://www.switchscores.com/games/7423/primordia - URL is hanging, so I've blanked it out: https://www.nintendo.co.uk/Games/Nintendo-Switch-download-software/Primordia-2172519.html

**Comment by benbarden** [comment]
Duel Princess and Duggy are missing from Google.

Primordia is there, but still hanging.

**Comment by cosmo0** [comment]
One Finger Death Punch has been released in the US but not EU. Not sure what to do, maybe you could skip US links for image download?

Real Time Battle Shogi Online: fixed

Duel Princess has been de-listed because of some controversy.

Having been released recently, I'm willing to bet Duggy and Primordia have been removed following some rating issue (it happens pretty often). Maybe they will come back later, maybe they won't.

**Comment by benbarden** [comment]
This was mostly data fixes - thanks for sorting. One Finger Death Punch isn't a big issue, I can put in a fix if this happens more in future.
