### ISSUE TITLE
API for Playnite Extension

### ISSUE THREAD

**Issue by minhnhattonthat** [benbarden/switchscores#163]
Hi, I plan to create an extension for [Playnite](https://playnite.link) (a game library front-end), which  can retrieve data from Switch Scores to populate metadata for switch games.

I have developed [one](https://github.com/minhnhattonthat/playnite-nintendo-metadata-plugin) that use data from Nintendo directly, but as sometimes games got delisted, and Nintendo may retired the APIs, so a secondary source is helpful.

I also checked that issue #19 has requested the API, though there are some fields missing

- [x] tags
- [x] developers name
- [x] publishers name
- [x] list of reviews
~~square image uploaded on switchscores.com~~
~~header image uploaded on switchscores.com~~

So may I request if you could update the API to include the above fields? I would really appreciate that! Thanks!

**Comment by benbarden** [comment]
Hey @minhnhattonthat , most of this should be ok - a few comments:

- tags aren't filled in for a lot of games - this became very time-consuming so we stopped. Happy to share the data if it's there, but please note it is not always there. The category should be much more consistent - pretty much every game is categorised.
- developer names - that's fine, I will add those. As with tags, a lot of the data isn't filled in. Nintendo stopped including them on their game pages, and Wikipedia stopped including these details too. So the data is quite difficult to find.
- publisher names - also fine.
- list of reviews - also fine.
- images - the Switch Scores images are not included because I want to discourage sites from embedding our images directly. If a game API response contains "dspNintendoCoUk" then you can grab the images from there. Not all games have those however - for those that don't I can provide an alternative Nintendo URL, where I downloaded the images from.

**Comment by minhnhattonthat** [comment]
hi @benbarden 

Appreciate your prompt updates!

I have emailed you for the invite code.

For tags field, I'm happy if they are available, and will handle the case when it's empty.

Looking forward to testing out the new API!

**Comment by benbarden** [comment]
Tags are now available, so I'll close this. Thanks for the ideas! :)
