### ISSUE TITLE
Add more infos from various sources

### ISSUE THREAD

**Issue by cosmo0** [benbarden/switchscores#38]
Here are a few ideas (some taken from other sites) of data that would enrich the user experience:

From Nintendo (if they're in the API, or scrapped from the page):

- Game size
- Age rating & descriptions (violence...)
- Controllers
- Features (amiibo, handheld...)
- Languages
- Description
- Screenshots/videos

From other sites (if they have an API):

- Steam review summary and link (see #16 )
- Metacritic score and link
- Amazon link for physical games (could be sponsored)
- Data from Howlongtobeat
- Price history from DekuDeals or Psprices

**Comment by cosmo0** [comment]
Add also the info on whether a demo exists.

A link to the official YouTube trailer could be added manually (see SensCritique).

Display some of these infos in games lists: number of players, demo, age rating.

**Comment by benbarden** [comment]
Thanks for all the ideas! Going through each idea in turn:

- Game size: not in the API
- Age rating: in the API, so it's possible, though I'm not sure how many people would find it useful
- Controllers: in the API, might need a bit of work to bring the info into a usable format. compatible_controller might have some useful values in it
- Features: in the API, could use maybe play_mode_tv_mode_b, play_mode_handheld_mode_b, and play_mode_tabletop_mode_b for this. Unsure of where Amiibo info is stored, although I think that wouldn't be useful to include
- Languages: not sure it's that useful to list these out
- Description: unfortunately, this isn't in the API. I wish it was. We do have "excerpt", which for A Short Hike is "Hike, climb, and soar through the peaceful mountainside landscapes of Hawk Peak Provincial Park". So that might be useful, but it's pretty short (like the game!)
- Screenshots/videos: we already talked about this one - not in the API and also not particularly easy to scrape. We do have a video URL field already but it isn't currently displaying on the site as most of the videos aren't filled in
- Steam reviews: not sure how to do this, but let's leave it for the other issue
- Metacritic score and link: I sometimes think of Switch Scores as a kind of "Metacritic for Switch". I don't think that having the Metacritic score shown on the site is a good idea - it could confuse people. (Why have two scores?)
- Amazon link: I have functionality for that, but most games aren't on Amazon anyway, so it's not very valuable
- Howlongtobeat: could be useful, just not sure how to do it
- Price history: I don't think this is right to include on Switch Scores - I don't see it being very useful. If people really want to see it they can always find it elsewhere.
- Demos: probably in the API - I don't know how useful it is to have on the site though.
- Youtube trailer: you already mentioned screenshots/videos - the videos I've been adding have only been the trailers. They are the most logical videos to add in my view.
- Displaying players, demo, age rating in games lists: I think this will clutter up the page - there's a lot that could be displayed but the pages are already long, and adding more just makes them longer.

One other idea from me:
- Multiplayer: this might be useful (I don't think you mentioned it) - the field multiplayer_mode could be useful

My general approach for Switch Scores has been to keep things clean and not add every possible bit of information to the page. I feel it's important to not try to be everything to everyone. At its core Switch Scores is about the rankings, helping people to find games they might enjoy, and providing tools to keep track of your collection or wishlist are good things in my view.

Some of these are things that I think other sites can do a better job of. Some are quite difficult to do, as they don't exist in the API and would need to be scraped. Scraping isn't much fun to do, it's time-consuming, and it's very brittle as it can break with even the smallest change to a site's HTML. Plus some sites aren't keen for people to scrape them and it could get me banned.

If it was possible to add all of these fields, the next challenge is that they probably all need to be added to an advanced search page too. Other than the time needed to build this, I'm keen to not try to reproduce what is already available in the eShop and on Nintendo.co.uk. Some filters may be useful, but I'd like to avoid going overboard.

I think it would be really helpful if we could try to stick to one idea per thread, as there's a lot to go through here. I think it's easier to comment on things if you can split them up a bit :)

**Comment by cosmo0** [comment]
I understand wanting to keep the site clean ; I've written all ideas I had in case you found them interesting enough ^^

I didn't wanted to spam with a thousand issues. Maybe we could keep this one for discussing ideas, and create issues for the ones you deem worth pursuing?

---

Age rating: it's useful for people who look for games they can play with their kids. It's not a end-all-be-all to whether a game is appropriate for kids: hardcore racing sims are rated PEGI 3 because they don't feature violence or anything; and each kid is sensitive to different things. But it can eliminate violent or scary games when you're looking for something to play with your 5-yo.

Language is not useful to you, a native english speaker, because all EU games have english :) In many countries, a lot of people have enough english knowledge to browse a website, but not enough to play a full game. I see a lot of people refusing to play very good games just because they don't have french language option.

Description: excerpt might be better than nothing, but not by much.

Demo would be very cool if it's in the API. It could be a way to get people interested in an unranked or mixed-reviews game, like "hey I'm not sure but I can try it myself".

For the Youtube trailers, I didn't have the time to expand when I wrote it: SensCritique (a french "Metacritic 100% by users") has a wiki-like feature to edit pages, and users can add trailers links to Youtube page:

<img width="736" alt="Capture d’écran 2021-01-24 à 00 34 21" src="https://user-images.githubusercontent.com/3973850/105617029-f08e2300-5ddb-11eb-963c-d0d78ea5713b.png">

It would require users to fill these out (if they exist, which they often do), but it would allow you to easily insert videos in the page, without hosting anything, without upload, etc, just embed the Youtube player: more info for the user, not too much work for you.

**Comment by benbarden** [comment]
You make good points :)

I'll respond to these suggestions properly when I have a chance - for now I wanted to mention that I've added a discussion label that can be used for general comments that aren't for one specific change. I suggest that the goal of a discussion is to find out what changes could be made, those changes can then be created in separate issues, and the discussion closed once it reaches a natural end. Sound ok?

**Comment by benbarden** [comment]
PS. Does it let you assign labels yourself?

**Comment by cosmo0** [comment]
> Sound ok?

Yes!

> Does it let you assign labels yourself?

No. I think you have to go to settings > manage access > invite a collaborator, but I'm not sure, and I'm not sure, and I'm not sure it's worth the trouble :)

**Comment by benbarden** [comment]
@cosmo0 we now have discussions! 🎉  Unfortunately, there isn't a way to convert this issue to a discussion - could you copy your comments and start a new discussion here?
https://github.com/benbarden/switchscores/discussions

**Comment by cosmo0** [comment]
Discussion moved here: https://github.com/benbarden/switchscores/discussions/47
