### ISSUE TITLE
Allow registration through other accounts than Twitter

### ISSUE THREAD

**Issue by cosmo0** [benbarden/switchscores#56]
Right now users can only register if they have a Twitter account.

Allowing users to register through other OAuth/OpenID providers would probably get more people to register.

Sensible additional providers could be:

- Facebook
- Google
- Microsoft
- Instagram?

**Comment by benbarden** [comment]
Google might be worth adding. Also, I might bring back the option to register with email/password, but it generated a lot of spam. Anti-spam solutions such as CAPTCHA or ReCAPTCHA only go so far.

My hesitation with adding the others is because having a lot of options can be counter-intuitive if you use all of the providers available. I can never remember which option I used for each site. You then end up with duplicate accounts if the email addresses are different.

All of the publicity I'm doing is on Twitter and there is a large amount of people talking about the Switch there, so we might not be missing a lot of people by only offering Twitter. I don't plan to publicise the site elsewhere - it's a lot of extra effort for very little gain.

I don't think I've ever seen Microsoft as a login option!

**Comment by cosmo0** [comment]
Yeah open registration with a captcha is not worth the trouble. Spambots are very good these days.

I don't think having a lot of options is problematic. If you log with the wrong account you just log out then log back in.

Maybe Microsoft is just for MS products, I haven't checked.

**Comment by cosmo0** [comment]
Epic Games allows connection through Nintendo account. That's interesting.

![image](https://user-images.githubusercontent.com/3973850/106435668-7876cb80-6473-11eb-8899-b904d2fca738.png)

**Comment by benbarden** [comment]
Just so you know, I've added invite codes so it's possible to sign up with email/password again. Each code is unique. I've set it up so that you can have unique, single-use codes, as well as multi-use codes. The codes are an owner-only tool - let me know if anyone wants to sign up with email/password and I can send a code.
