### ISSUE TITLE
Generate images on series landing page

### ISSUE THREAD

**Issue by cosmo0** [benbarden/switchscores#57]
Right now "series" is a very raw and rough list.

I suggest combining up to 4 games covers in the list such as here: https://codepen.io/cosmo0/pen/jOVOJav

First 4 by name or release date or score, I'm not sure.

**Comment by benbarden** [comment]
It is probably a lot simpler if I add a field so each series can have an image attached to it, and then make the images manually. Would you like to make some images? :)

**Comment by cosmo0** [comment]
Honestly, I think it'd be better if it was automatic, this way you could display the most recent or highest-rated without having to change the image. If you want a single image, it could be generated using php/imagemagick?

**Comment by benbarden** [comment]
OK, I've made the title more specific.

**Comment by benbarden** [comment]
Here you go - https://www.switchscores.com/games/by-series

A couple of notes:

- Games with the highest ratings are the ones shown. They do need to have packshots in the system though (pretty much all should)
- It works with 2 or 3 images (Bayonetta has 2). I've not seen any examples where we only have 1, but that will probably have some grey space as it uses the square packshots, and the final generated image is wider
- Blank images are because there are no games for those series (the ones that are now collections). We will delete those when I've done #100 
- Images will update overnight on a cron

**Comment by cosmo0** [comment]
Really cool!

Just a few remarks:

- could you center the "inner images"? Most logos have a centered point-of-interest, seeing only the left part is weird
- could you reduce the height a little? (like half) That way more of the logos would fit, and the page would be smaller.
- could you increase the vertical spacing between rows?
- you could regenerate them every week, no need to do it every day.

**Comment by benbarden** [comment]
Centring the images works just about ok. The cropping now starts at 25px from the left rather than 0px. Any more and it cuts into the text on a lot of the images.

I've made the images smaller, but the solution with the height is to allow up to 4 columns. Everything is now a bit smaller.

Rows now have additional spacing.

Regenerating images isn't a heavy job, and I'd rather not wait a whole week for them to update.

**Comment by cosmo0** [comment]
Nice! Much better :)

**Comment by cosmo0** [comment]
Nevermind, there's a bug when a series title is too long
<img width="898" alt="Capture d’écran 2021-05-29 à 14 14 26" src="https://user-images.githubusercontent.com/3973850/120069831-3871cf00-c088-11eb-829d-072202327775.png">

**Comment by benbarden** [comment]
Options:

Change to 2 columns rather than 3.

Make the text smaller and reduce the spacing. That won't be perfect though.

Any thoughts?

**Comment by cosmo0** [comment]
You can reduce the font size and the left padding (to left-align the text and the image), but you can also crop the text using an ellipsis: https://developer.mozilla.org/en-US/docs/Web/CSS/text-overflow

**Comment by benbarden** [comment]
Should look better now.

**Comment by cosmo0** [comment]
Nice! 👍
