### ISSUE TITLE
Games with missing publishers

### ISSUE THREAD

**Issue by cosmo0** [benbarden/switchscores#65]
I've taken a look at the games with missing publishers, but most of them have one in the API. How comes they're not filled in the game's data if the info is in the API?

Plus, not-released games often don't have these infos, so maybe they shouldn't appear in the list?

**Comment by benbarden** [comment]
The data is pretty messy, so can't really be imported as-is. However, I do have some code that cleans it up a bit. See here:

https://github.com/benbarden/switchscores/blob/718b29c47af634db184c8f13c7e92f1d992d0446/app/Services/DataSources/NintendoCoUk/Parser.php#L195

This is one part of the process. The basic process of getting data from the API is as follows:

- load the raw data from the API and save it as a DataSourceRaw model, one per game (and a game also has one model per data source - Wikipedia would be an additional source)
- parse the data into a usable format, clean it up, and save it as a DataSourceParsed model (again one per game)
- update some of the data on the Game model automatically, such as the US and Japanese release dates (this only exist in Wikipedia). Other is held back and reviewed manually - this is why we have conflicts with prices, players, EU release dates, developers, and publishers, as they are not automatically applied

For data that isn't copied to the Game model, the DataSourceParsed model holds some data that can be displayed on the site, but it's not where the "master" data lives. For publishers, the master data is a link between the Game model, GamePublisher model, and Partner model. It's not just a text field, as the Partner model holds additional data that's useful. Because of this, it isn't just a case of overwriting the text each time. I would need to check if a Partner exists with that name first, and if so, link it.

However, it's not automatically updated at the moment because the data isn't always correct. Wikipedia might be wrong too, but the reason I pull data from both is to help with comparing the values from multiple sources. Sometimes there are multiple publishers and one is not in the API. Sometimes Nintendo has the wrong info. It is hard to find out what it's meant to be, as not all publishers have comprehensive websites or press kits to show all of their games.

I've done a lot of manual curation of the data on the site, to improve its overall quality and try to reduce the amount of bad data in the API. The downside, of course, is that it adds extra effort to keep it updated.

A couple of things I could do to make this better:

- auto-link the publisher if the name matches. (But what if it's wrong?)
- if it doesn't match, we could have a list of "unmatched" items. Those could either be created one by one, or ignored.

Did that make sense - and do you have any other ideas?

**Comment by benbarden** [comment]
I've also added some unit tests for the publisher parser code, which should show you some examples of the type of data that is being cleaned up, along with the expected output from the parser.

https://github.com/benbarden/switchscores/blob/01d152565ad8a6d996ab4477b49512d9676a9bdd/tests/Unit/Services/DataSources/NintendoCoUk/ParsePublishersTest.php

For example, `2 Zombie Games Co., Ltd.` comes out as `2 Zombie Games`.

**Comment by cosmo0** [comment]
> (I'm sure this could be cleaned up a bit!)

````php
$replace = [
  'Co.,Ltd' => '',
  ' Ltd.' => '',
  ' ENTMT' => ' Entertainment'
];
foreach ($replace as $origin => $replacement) {
  $parsedPublishers = str_replace($origin, $replacement, $parsedPublishers);
}
````

Auto-matching would be great. If you want to check before validating, it could suggest an entry with an "accept" button in the list. That way it's just a series of clicks to validate entries, and only manually check when you have a doubt or the entry doesn't exist.

Do you have an example of wrong publisher in the API ? That seems legally a bit dangerous for Nintendo, I'm surprised. Games can be published by a different publisher on each platform or in each region (EU/US/JP), they can change publisher over time (Stardew Valley switched to self-publication), and they can have a different publisher for physical and digital version (The Binding of Isaac's digital and physical versions are not compatible). It's a mess, and I wouldn't trust Wikipedia on this, when researching older games for my site I saw too often how wrong they were.

In the end, I don't think having a wrong publisher on a bunch of games is a very big deal. Having the correct publisher/developer for most games would be much more useful, like "I like this one's output, what else do they do", especially with publishers that specialize in a style (like Artifex Mundi doing 99% point & clicks).

**Comment by benbarden** [comment]
Thanks, I'll do that for now - regex might help too, but that'll take a bit more time. I don't think the replace code needs the second part of the array - almost all of the values are replaced with an empty string anyway. For the last two, I'll leave them as they are.

This page will show you some differences:
https://www.switchscores.com/staff/data-sources/differences/nintendo-co-uk/publishers

For the game "They Came From the Sky" (4033):

Nintendo UK API publisher - Hook Games
Nintendo.com developer - Hook.gg, FobTi interactive
Nintendo.com publisher - Nestor Yavorskyy
Wikipedia developer - FobTi Interactive,Hook Games
Wikipedia publisher - Nestor Yavorskyy

And just for comparison:
Steam developer - FobTi interactive
Steam publisher - FobTi Interactive,Hook.gg

Hook.gg is probably the same as Hook games.

Maybe Nestor Yavorksyy is the publisher in the US, and Hook Games the publisher in the UK? It's not entirely wrong, but it's quite difficult to unpick all of this. I know Wikipedia can be quite US-focused with its data, but they do sometimes show other publishers for different regions.

It might be worth going back to the reasons for getting publishers (and developers) on the site:

- It gives a way to find more games by a particular publisher or developer.
- It gives publishers and developers more of a reason to register for the site. Mind you, this is mostly for giving them a way to contact reviewers, and they don't need their games to be linked up correctly for that to work.

Would it help if each publisher on a game could have a region? It could get complicated, but it would help where there's more than one publisher for a game.

I'd like to do something here, but I'm not sure of the best options seeing as the data is unreliable.

**Comment by cosmo0** [comment]
> Thanks, I'll do that for now - regex might help too, but that'll take a bit more time.

Regexes could help a bit to trim down the list, but I'm not sure they're worth the trouble. As they say: "you have a problem, you use regular expressions, now you have two problems".

> Maybe Nestor Yavorksyy is the publisher in the US, and Hook Games the publisher in the UK? It's not entirely wrong, but it's quite difficult to unpick all of this. I know Wikipedia can be quite US-focused with its data, but they do sometimes show other publishers for different regions.

From Nestor Yavorksyy's Facebook page, he's the founder of Hook games. So maybe he published under his name in a region and under his company's in another, like for administrative reasons?

Also, sometimes publishers work in tandem: for instance, Circle Ent. and Flyhigh Works are different companies that publish the same games for US/EU (Flyhigh) and JP (Circle) regions.

Your list contains many examples of "same company with a different name" that can be ignored. I'll go through them when I start working on companies, if you want.

> Would it help if each publisher on a game could have a region? It could get complicated, but it would help where there's more than one publisher for a game.

As long as you don't have a link to the US site and the price in $, I don't think it's useful.

> I'd like to do something here, but I'm not sure of the best options seeing as the data is unreliable.

I think the best compromise for now is easing up the validation. In the "games missing publisher" page, you could try to match the Nintendo data with an existing company in the DB, and if it does, add an "accept" link. That way I could go through everything that matches nicely, while still being able to check if it looks iffy.

About the rest, I don't think it's a very big deal. Having a nice "publisher" field is only useful for a few publishers:

- the "big" (Nintendo, Capcom, Square...) with "big games"
- the "focused" that publish a lot of similar games (Artifex Mundi, Kairosoft...)
- the ones that have a consistently good catalog (Devolver Digital...) or just consistent in scope (Ratalaika, PQube...)

As a player, the rest of the publishers are not that interesting to know, and I'm not sure publishers really need to be linked to their games to be able to work. I don't think you should trouble yourself too much with that.

**Comment by benbarden** [comment]
> you have a problem, you use regular expressions, now you have two problems

I thought that was more of a Java quote 😄  "I have a problem - I decided to use Java - now I have a ProblemFactory" 😉  I guess it can apply in a few different cases!

You should now have access to the page where developers and publishers are set, as I updated the permissions on it. Take this game for example: https://www.switchscores.com/staff/games/partner/5312/list

Perhaps some additional buttons on that page would help.

**Comment by benbarden** [comment]
I'm going to close this - feels like more of a discussion. I'll start a new issue for adding buttons to the partners page in staff.
