### ISSUE TITLE
Sort by price doesn't sort by discounted price

### ISSUE THREAD

**Issue by cosmo0** [benbarden/switchscores#79]
- Open a category
- Open a "table" view (like "all ranked")
- Sort by price
- ➡️  the prices are sorted by "regular" price and not "discounted" price

**Comment by benbarden** [comment]
There's a bigger issue here - it isn't seeing the column as a number. So in a lowest-to-highest sort, £1.00 and £10.00 would appear first, with £9.99 appearing last.

Some docs here - https://datatables.net/reference/option/columns.type

However, applying the num-fmt to this column doesn't seem to do anything - perhaps because of the formatting for discounted prices.

I think I'll need to put the current price (discounted or not) in one column, and then put notes in a second column to say if it has been discounted. I'm not sure how useful that will be though, as it will be less obvious that there is a discount.

**Comment by benbarden** [comment]
@cosmo0 this is now fixed. Gives me an idea for a new Games on sale page, too!
